/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Amount;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-14T12:00:35.775Z")

@Api(value = "convert", description = "the convert API")
public interface ConvertApi {

    @ApiOperation(value = "Convert amount", nickname = "convert",
            notes = "Converts a given amount in one currency to the corresponding amount in an different currency",
            response = Amount.class, tags = {"public",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The converted amount", response = Amount.class),
            @ApiResponse(code = 404, message = "Currency Not Found") })
    @RequestMapping(value = "/convert",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Amount> convert(
            @NotNull
            @ApiParam(value = "The amount to convert", required = true)
            @Valid @RequestParam(value = "amount", required = true)
                    Double amount,
            @NotNull
            @ApiParam(value = "Code of the input curency", required = true)
            @Valid @RequestParam(value = "inputCurrency", required = true)
                    String inputCurrency,
            @NotNull
            @ApiParam(value = "Code of the output curency", required = true)
            @Valid
            @RequestParam(value = "outputCurrency", required = true)
                    String outputCurrency);
}
